server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service # user 服务名称

mybatis:
  type-aliases-package: cn.xbw.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.xbw: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url: # eureka 地址
      defaultZone: http://localhost:10086/eureka