server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: user-service # user 服务名称
  cloud:
    nacos:
#      server-addr: localhost:8848 # nacos 服务地址
      discovery:
        cluster-name: GZ # 集群名称  GZ广州  SH上海
        # weight: 1.0 # 权重


mybatis:
  type-aliases-package: cn.xbw.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.xbw: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: # eureka 地址
#      defaultZone: http://localhost:10086/eureka