logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 192.168.0.100 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: xbw # 用户名
    password: 12345678 # 密码



