server:
  port: 10086 # eureka 服务端口
spring:
  application:
    name: eureka-server # eureka 服务名称
eureka:
  client: # eureka 本身也算是一个服务，所以把eureka注册进eureka
    service-url:  # eureka 地址
      defaultZone: http://localhost:10086/eureka
