server:
  port: 8081
spring:
  application:
    name: itemservice
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/xbw_db?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.xbw.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.xbw: debug
  pattern:
    dateformat: HH:mm:ss:SSS